import type { Metadata } from "next";
import { Rubik } from "next/font/google";
import "./globals.css";
import Navbar from "@/shared/components/navbar";
import { SidebarProvider } from "@/context/sidebarContext";
import { Providers } from "./providers";

const rubik = Rubik({
  subsets: ["latin"],
  variable: "--font-rubik",
  display: "swap",
  weight: ["300", "400", "500", "600", "700", "800", "900"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${rubik.className} antialiased font-rubik overflow-x-hidden`}
      >
        <Providers>
          <SidebarProvider>
            <Navbar />
            {children}
          </SidebarProvider>
        </Providers>
      </body>
    </html>
  );
}
